### ISSUE TITLE
Validation utilities

### ISSUE THREAD

**Issue by SpicyCactuar** [Wolox/wolmo-core-android#29]
The idea is to extract common validation logic/patterns in order to facilitate form development.

I leave a couple of ideas:

### `Form`alizing it up

I've looked solutions in other frameworks and platforms, and i arrived to one i like which is the [Flutter approach](https://flutter.rocks/2017/10/17/validating-forms-in-flutter/).

It has a `Form` object which hooks the validation functions to the corresponding `View`s and *emits only* valid forms/fields.

The only downside i see to this approach is configuration wise. It's all done on the `View`'s side. What i came up with for this is for the `Presenter` to provide the `Form` already constructed and then let the `View` hook up the necessary stuff. It's difficult to generalize, though.

### `Validator`s FTW

A more simple utility is providing `Validator` objects for the common cases in field validation. This was something @alvarez-fabian had started doing in GreenCommuter.

This is something i believe *we should do regardless of the first idea* because the validation logic is something that in 99% of the cases is repeated.

What do you guys think?

**Comment by emalamela** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wolmo: Extraer código de validators](https://trello.com/c/OvqlvRNp/5-wolmo-extraer-c%C3%B3digo-de-validators)
