### ISSUE TITLE
Nullability annotations

### ISSUE THREAD

**Issue by SpicyCactuar** [Wolox/wolmo-core-android#30]
A QOL change for our open source repos is adding `@NonNull` and `@Nullable` to, at least, the `public` and protected methods.

- [ ] https://github.com/Wolox/WoloxAndroidBootstrap
- [ ] https://github.com/Wolox/wolmo-core-android
- [ ] https://github.com/Wolox/wolmo-networking-android
- [ ] https://github.com/Wolox/wolmo-maps-android

Besides this, i like the ['Non-null by default' Square has been pushing](https://medium.com/square-corner-blog/non-null-is-the-default-58ffc0bb9111). Adding this would lower the amount of effort we have to make.

Any thoughts?

**Comment by emalamela** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wolmo: Añadir documentación y anotaciones a los métodos de wolmo](https://trello.com/c/TsjWUQy2/9-wolmo-a%C3%B1adir-documentaci%C3%B3n-y-anotaciones-a-los-m%C3%A9todos-de-wolmo)
