### ISSUE TITLE
Multipurpose @Inject annotation

### ISSUE THREAD

**Issue by foviedoITBA** [Wolox/wolmo-core-android#40]
## Problem

The `@Inject` annotation in Dagger is used both for requesting injection on a member and for declaring "injectability" in a constructor or method. Since these are two different tasks, we should have two different annotations.

## Possible solution

Create two annotations:
* `@Injectable` or `@Injector`: can only be used for methods and constructors to signify that calling them is a means of obtaining an instance to inject somewhere else
* `@Inject` or `@InjectMe`: can only be used on fields to signify that they are expected to be injected an instance of whatever type they are

I think this would make the code a little cleaner. I would be glad to code this for wolmo-core-android, though I have no experience with Kotlin so far. I am open to suggestions on better names or alternative solutions.

**Comment by emalamela** [comment]
Indeed, it's not an ideal case.

But, on the other hand, how much value do you see in investing time into this?

It's an industry standard practice to use this annotation. I don't see any practical value in doing this.

**Comment by foviedoITBA** [comment]
The added value would not be a lot, but that doesn't mean it's not worth investing some effort into it. As for the effort, it feels to me like it's a very automatable task: replace every instance of `@Inject` on a member field with `@InjectMe` and every instance of `@Inject` on a method or constructor with `@Injector` (for instance) plus creating two two-line annotations.

Being an industry standard practice does not mean we cannot have our own wrapper around it. Internally we would be using the `@Inject` annotation, so we're not deviating from standard practices in any way.

The main reason for this issue coming to life is the harsh comments I heard from the Android team about Dagger having the same annotation for different purposes. If it's not a big deal, then we can close this issue, but I hope I don't ever hear such over-exaggerated complaints again.
