### ISSUE TITLE
RequireArguments and RequireArgument.

### ISSUE THREAD

**Issue by dylan-muszel** [Wolox/wolmo-core-android#43]
Using `requireArgument` to get `arguments!!` and `requireArgument` to get a specific argument not null.

**Comment by emalamela** [comment]
I think it's a great idea!

I happen to code utilities every time I have to use them. Definitely has value.

How would you approach the `requireArgument` method when there's no API to fetch a truly generic argument?

**Comment by dylan-muszel** [comment]
It's blocked until it's migrated to Kotlin. 😕

**Comment by dylan-muszel** [comment]
`requireArgument` is implemented since version 4.0.0
